// 由 build.rs 自动生成，请勿手改

/// 编译时嵌入的枪械模板：(名称无后缀, PNG 字节)
pub const TEMPLATE_FILES: &[(&str, &[u8])] = &[
    (r#"301"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/301.png"))),
    (r#"3030"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/3030.png"))),
    (r#"car"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/car.png"))),
    (r#"eva8"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/eva8.png"))),
    (r#"g7"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/g7.png"))),
    (r#"lstar"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/lstar.png"))),
    (r#"r99"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/r99.png"))),
    (r#"re45"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/re45.png"))),
    (r#"三重"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/三重.png"))),
    (r#"专注"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/专注.png"))),
    (r#"单2020"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/单2020.png"))),
    (r#"单莫桑比克"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/单莫桑比克.png"))),
    (r#"双2020"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/双2020.png"))),
    (r#"双莫桑比克"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/双莫桑比克.png"))),
    (r#"和平"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/和平.png"))),
    (r#"哈沃克"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/哈沃克.png"))),
    (r#"哨兵"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/哨兵.png"))),
    (r#"喷火"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/喷火.png"))),
    (r#"复仇"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/复仇.png"))),
    (r#"大炮"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/大炮.png"))),
    (r#"小帮手"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/小帮手.png"))),
    (r#"平行"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/平行.png"))),
    (r#"弓"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/弓.png"))),
    (r#"暴走"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/暴走.png"))),
    (r#"滋崩"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/滋崩.png"))),
    (r#"猎兽"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/猎兽.png"))),
    (r#"獒犬"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/獒犬.png"))),
    (r#"电冲"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/电冲.png"))),
    (r#"赫姆洛克"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/赫姆洛克.png"))),
    (r#"转换者"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/转换者.png"))),
    (r#"长弓"#, include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/gun_template/长弓.png"))),
];
